homeassistant:
  name: Powermix Dev
  latitude: 60.0
  longitude: 15.0
  elevation: 120
  unit_system: metric
  currency: SEK
  time_zone: Europe/Stockholm

# Pull in the usual dashboards, energy, automations etc.
default_config:

# Reduce log noise but surface Powermix debug output while developing.
logger:
  default: warning
  logs:
    custom_components.powermix: debug

# Use input numbers so you can tweak "live" power values from the UI.
input_number:
  main_power:
    name: Total Power
    min: 0
    max: 10000
    step: 10
    unit_of_measurement: W
    icon: mdi:flash
    initial: 4200
  heat_pump_power:
    name: Heat Pump Power
    min: 0
    max: 5000
    step: 10
    unit_of_measurement: W
    icon: mdi:fire
    initial: 1800
  ev_charger_power:
    name: EV Charger Power
    min: 0
    max: 11000
    step: 10
    unit_of_measurement: W
    icon: mdi:car-electric
    initial: 3200
  server_rack_power:
    name: Server Rack Power
    min: 0
    max: 3000
    step: 10
    unit_of_measurement: W
    icon: mdi:server
    initial: 450

# Expose template sensors with the "power" device class from the knobs above.
template:
  - sensor:
      - name: "Total Power"
        unique_id: powermix_total_power
        device_class: power
        unit_of_measurement: W
        state: "{{ states('input_number.main_power') | float(0) }}"
      - name: "Heat Pump"
        unique_id: powermix_heat_pump
        device_class: power
        unit_of_measurement: W
        state: "{{ states('input_number.heat_pump_power') | float(0) }}"
      - name: "EV Charger"
        unique_id: powermix_ev_charger
        device_class: power
        unit_of_measurement: W
        state: "{{ states('input_number.ev_charger_power') | float(0) }}"
      - name: "Server Rack"
        unique_id: powermix_server_rack
        device_class: power
        unit_of_measurement: W
        state: "{{ states('input_number.server_rack_power') | float(0) }}"
